"""tambah index pada package_name

Revision ID: 0876a88af900
Revises: 7f97fd44f857
Create Date: 2026-09-23 18:52:19.125599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0876a88af900'
down_revision = '7f97fd44f857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc_system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qc_system_package_name'), ['package_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc_system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qc_system_package_name'))
    # ### end Alembic commands ###
    