"""initial baseline

Revision ID: 377d6794b428
Revises: 
Create Date: 2026-09-10 04:25:50.810307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377d6794b428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc_system', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_project_task_id'), type_='unique')
        batch_op.create_unique_constraint('uq_project_package_task_id', ['project_name', 'package_name', 'task_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('qc_system', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_package_task_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_project_task_id'), ['project_name', 'task_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
