"""task_id unique per project+package, not just project

Revision ID: db2a3e1c4ba9
Revises: 377d6794b428
Create Date: 2026-09-10 04:26:02.006245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2a3e1c4ba9'
down_revision = '377d6794b428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc_system', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_project_task_id'), type_='unique')
        batch_op.create_unique_constraint('uq_project_package_task_id', ['project_name', 'package_name', 'task_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc_system', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_package_task_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_project_task_id'), ['project_name', 'task_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###